#!/usr/bin/env bash
# Prints the last n branches you've worked on in a repo.
#
# Download this script as "git-recent" (no extension), chmod it to be
# executable and put it in your path somewhere (e.g. /usr/bin). You can then
# use it via `git recent` from inside any git repo.
#
# Based on:
#   http://stackoverflow.com/a/5188364
#   https://gist.github.com/jordan-brough/48e2803c0ffa6dc2e0bd
#
# - Shiva Ghose and Elliot Branson

usage()
{
  echo "Prints the last 'n' git branches you've worked on."
  echo "usage: git recent [-n lines]"
}

while getopts "hn:" opt; do
  case $opt in
    h)
      usage
      exit 1
      ;;
    n)
      NUM=$OPTARG
      ;;
    \?)
      usage
      exit 1
      ;;
  esac
done

NUM=${NUM-10} # default to 10 lines

# Print the last `n` branches that were modified locally:
git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))' | tail -n $NUM
